import { StyleSheet } from 'react-native';
import { Colors, Radius } from '../config/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  scroll: { padding: 20, paddingBottom: 40 },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  greeting: { fontSize: 14, color: Colors.textSecondary },
  name: { fontSize: 22, fontWeight: 'bold', color: Colors.text },
  mapBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: Colors.cardElevated,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cards: { gap: 10, marginBottom: 16 },
  quickCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Colors.card,
    borderRadius: Radius.md,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  quickIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickContent: { flex: 1 },
  quickLabel: { fontSize: 12, color: Colors.textSecondary },
  quickValue: { fontSize: 13, color: Colors.text, fontWeight: '500', marginTop: 2 },
  accelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.card,
    borderRadius: Radius.sm,
    padding: 10,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  accelText: { flex: 1, fontSize: 13, color: Colors.textSecondary },
  accelDot: { width: 8, height: 8, borderRadius: 4 },
  sosWrap: { alignItems: 'center', marginBottom: 24 },
  sosLabel: {
    fontSize: 11,
    color: Colors.textSecondary,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  sosHint: { fontSize: 12, color: Colors.textMuted, marginBottom: 28, marginTop: 4 },
  sosOuter: {
    width: 178,
    height: 178,
    borderRadius: 89,
    backgroundColor: Colors.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: 'rgba(255, 255, 255, 0.34)',
  },
  sosInner: {
    width: 136,
    height: 136,
    borderRadius: 68,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOpacity: 0.85,
    shadowRadius: 24,
    elevation: 14,
  },
  sosText: { fontSize: 26, fontWeight: 'bold', color: Colors.text, marginTop: 18 },
  simBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.primary,
    borderRadius: Radius.md,
    paddingVertical: 12,
    backgroundColor: Colors.primarySoft,
  },
  simBtnText: { color: Colors.primary, fontSize: 14, fontWeight: '600' },
});
